export {default as Heading} from './heading';
export {default as TestSection} from './test-section'
export {default as HeroHomepage} from "./heroHomepage"
export {default as Space} from './space'
export {default as CollectionGrid} from './collectionGrid'
export {default as TextContentCenter} from "./textContentCenter"
export {default as HeroText} from "./heroText"
export {default as EventsCarousel} from "./eventsCarousel"
export {default as Gallery} from "./gallery"
export {default as ImageWithText} from "./imageWithText"
export {default as BannerWithText} from "./bannerWithText"
export {default as RestaurantsCarousel} from "./restaurantsCarousel"
export {default as HeroWithText} from "./heroWithText"
export {default as Details } from "./details"
export {default as Team} from "./team"
export {default as News} from "./news"
export {default as Newsletter} from "./newsletter"
export {default as Hero} from "./hero"
export {default as Events} from "./events"
export {default as NewsContent} from "./newsContent"
export {default as MoreNews} from "./moreNews"
export {default as Contact} from "./contact"
export {default as Richtext} from "./richtext"